
#ifndef USB_ADDRESSES_H
#define USB_ADDRESSES_H

/*
 * Due to using the FS USB of the STM32 F4 only 1-3 can be used as addresses
 * OUT 1-3, IN 1-3
*/

// CDC ACM (USB UART)

//INTERFACES
#define USB_CDC_ACM_CONTROL_INTERFACE_ADDR 1
#define USB_CDC_ACM_DATA_INTERFACE_ADDR 2

//ENPOINTS
#define USB_CDC_ACM_CONTROL_EP_ADDR USB_ENDPOINT_ADDR_IN(1)
#define USB_CDC_ACM_DATA_TX_EP_ADDR USB_ENDPOINT_ADDR_IN(2)
#define USB_CDC_ACM_DATA_RX_EP_ADDR USB_ENDPOINT_ADDR_OUT(1)

//STRINGS
#define USB_CDC_ACM_DEVICE_NAME_STRING_ID 1


// AUDIO

//INTERFACES
#define USB_AUDIO_CONTROL_INTERFACE_ADDR 3
#define USB_AUDIO_MIC_STREAMING_INTERFACE_ADDR 4
#define USB_AUDIO_SPEAKER_STREAMING_INTERFACE_ADDR 5

//ENDPOINTS
#define USB_AUDIO_MIC_STREAMING_EP_ADDR USB_ENDPOINT_ADDR_IN(3)
#define USB_AUDIO_SPEAKER_STREAMING_EP_ADDR USB_ENDPOINT_ADDR_OUT(2)

//STRINGS
//this does not work atm
#define USB_AUDIO_MIC_DEVICE_NAME_STRING_ID 4

#endif